[project]
name = "tim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "avro>=1.12.0",
    "fastavro>=1.11.1",
    "minio>=7.2.15",
    "pypdf>=5.5.0",
    "pypdf2>=3.0.1",
]
